name: "Sync npm"
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync_npm:
    name: "Sync npm"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Using Node v14.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "14.x"
      - name: Append recent counts
        run: node run.js
      - name: Configure GIT
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Commit
        run: git commit -a -m "Append new counts"
      - name: Push
        run: git push
